snmp:
  id: router-{{ index }}
  interval: 120s
  # This device is slow to enumerate SNMP interfaces, so we need to increase the timeout
  timeout: 60s
  exclude: |
    ifType != 'ethernetCsmacd'
  red: |
    ifOperStatus == "up" and ifSpeed < 1000000000
  target:
    host: 192.168.1.2
    community: public
