version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: serde
    versions:
    - 1.0.124
  - dependency-name: tokio
    versions:
    - 1.3.0
  - dependency-name: serde_yaml
    versions:
    - 0.8.16
