version: 1
server:
  port: 8000
  static: static

monitor:
  dir: monitor.d

ui:
  visualizations:
    - title: "Infrastructure Status Table"
      description: "Status table showing the health of infrastructure components"
      type: "table"
    - title: "D3 Infrastructure Diagram"
      description: "A D3.js visualization showing infrastructure components with status colors"
      type: "iframe"
      url: "/d3.html"
      inject: true

css:
  # Use metadata to get prettier colors for the d3 diagram
  metadata:
    red:
      color: "#fa897b"
    yellow:
      color: "#ffdd94"
    green:
      color: "#d0e6a5"
  rules:
    # Style the HTML/SVG with the appropriate status color
    - selectors: "
        #{{monitor.id}},
        [data-monitor-id=\"{{monitor.id}}\"]
      "
      declarations: "
        background-color: {{monitor.status.css.metadata.color}} !important;
        fill: {{monitor.status.css.metadata.color}} !important;
      "
    # Add some text for the status/return value of the script
    - selectors: "
        #{{monitor.id}} td:nth-child(2)::after
      "
      declarations: "
        content: \"status={{monitor.status.status}} retval={{monitor.status.code}}\"
      "
    # Add the full description to the table
    - selectors: "
        #{{monitor.id}} td:nth-child(3)::after
      "
      declarations: "
        content: \"{{monitor.status.description}}\"
      " 