version: 1
server:
  port: 8000
  static: static

monitor:
  dir: monitor.d

ui:
  visualizations:
    - title: "D3 Infrastructure Diagram"
      type: "row"
      columns:
      - type: "table"
        width: 2
      - type: "iframe"
        width: 3
        url: "/d3.html"
        inject: true

css:
  # Use metadata to get prettier colors for the d3 diagram
  metadata:
    red:
      color: "#fa897b"
    yellow:
      color: "#ffdd94"
    green:
      color: "#d0e6a5"
  rules:
    # Style the HTML/SVG with the appropriate status color
    - selectors: |  
        #{{monitor.id}},
        [data-monitor-id="{{monitor.id}}"]
      declarations: |
        background-color: {{monitor.status.css.metadata.color}} !important;
        fill: {{monitor.status.css.metadata.color}} !important;
