[package]
name = "stylus"
version = "0.9.14"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2018"
description = "Stylus (style + status) is a lightweight status page for home infrastructure."
license = "MIT"
repository = "https://github.com/mmastrac/stylus"
readme = "README.md"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
derive_more = "0.99.9"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
serde_json = { version = "1.0.57", features = ["raw_value"] }
serde-aux = "0.6.1"
humantime-serde = "1.0.0"
walkdir = "2.3.1"
handlebars = "3.4.0"
subprocess = "0.2.4"
log = "0.4.8"
env_logger = "0.7.1"
itertools = "0.9.0"
structopt = "0.3"
structopt-flags = "0.3.6"

[profile.release]
codegen-units = 1
incremental = false
