[package]
name = "stylus"
version = "0.9.14"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2018"
description = "Stylus (style + status) is a lightweight status page for home infrastructure."
license = "MIT"
repository = "https://github.com/mmastrac/stylus"
readme = "README.md"

[dependencies]
tokio = { version = "1.6.1", features = ["macros", "rt-multi-thread"] }
warp = "0.3.1"
derive_more = "0.99.14"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
serde_json = { version = "1.0.70", features = ["raw_value"] }
serde-aux = "2.2.0"
humantime-serde = "1.0.0"
walkdir = "2.3.2"
handlebars = "4.1.0"
subprocess = "0.2.7"
log = "0.4.14"
env_logger = "0.8.4"
itertools = "0.10.1"
structopt = "0.3"
structopt-flags = "0.3.6"

[profile.release]
codegen-units = 1
incremental = false
