version: 1
server:
  port: 8000
  static: static

monitor:
  dir: monitor.d

ui:
  title: "Infrastructure Monitoring"
  description: "Real-time infrastructure status with interactive diagram"
  visualizations:
    - title: "Infrastructure Diagram"
      description: "Interactive infrastructure overview with live status updates"
      type: "isoflow"
      config: "isoflow"

css:
  # Use metadata to get prettier colors for the isoflow diagram
  metadata:
    red:
      color: "#fa897b"
    yellow:
      color: "#ffdd94"
    green:
      color: "#d0e6a5"
  rules:
    # Style the isoflow diagram with the appropriate status color
    - selectors: |
        [data-monitor-id="{{monitor.id}}"]
      declarations: |
        background-color: {{monitor.status.css.metadata.color}} !important;
        fill: {{monitor.status.css.metadata.color}} !important;
