version: 1
server:
  port: 8000
  static: static

monitor:
  dir: monitor.d

ui:
  title: "Simple Network Status"
  description: "Network Status with Dynamic SVG Colors"
  visualizations:
    - title: "Network"
      type: "row"
      description: "Current status of all network components"
      columns:
        - type: "table"
        - type: "svg"
          url: "/network-diagram.svg"

css:
  # Use metadata to get prettier colors - note that we can add arbitrary string keys and values here
  metadata:
    red:
      color: "#fa897b"
    yellow:
      color: "#ffdd94"
    green:
      color: "#d0e6a5"
  rules:
    # Style the SVG with the appropriate status color
    - selectors: |
        [data-monitor-id="{{monitor.id}}"] > *
      declarations: |
        background-color: {{monitor.status.css.metadata.color}} !important;
        fill: {{monitor.status.css.metadata.color}} !important;
