version: 1
server:
  port: 8000

monitor:
  dir: monitor.d

ui:
  title: "SNMP Status"
  description: "SNMP Status"
  visualizations:
    - title: "SNMP Status"
      description: "SNMP Status"
      type: "row"
      columns:
        - type: "stack"
          width: 1
          stacks:
            - title: "Rack 1"
              rows:
                - id: "router"
                  size: "small"
                  layout: ~4x2 1 1x2
                  # Unifi Dream Machine Pro SE is weird, so we need to order the ports
                  # Bank of 8 ethernet ports, the 2.5 Gb port, then the two SFP ports
                  order: 15-22 12 3-4
                - id: "switch"
                  size: "small"
                  layout: 3x4x2 1
                - id: "switch-core"
                  size: "small"
                  layout: 3x4x2 2x2
        - type: "table"
          width: 3
