version: 1
server:
  port: 8000

monitor:
  dir: monitor.d

ui:
  title: "SNMP Status"
  description: "SNMP Status"
  visualizations:
    - title: "SNMP Status"
      description: "Current status of all SNMP components"
      type: "table"
    - title: "Rack 1"
      description: "Rack 1"
      type: "stack"
      stacks:
        - title: "Rack 1"
          rows:
            - id: "router"
              size: "small"
              layout: 3x1 4x2
            - id: "switch"
              size: "small"
              layout: 3x4x2 1
            - id: "switch-core"
              size: "small"
              layout: 3x4x2 2x2
