version: 1
server:
  port: 8000

monitor:
  dir: monitor.d

ui:
  title: "SNMP Status"
  description: "SNMP Status"
  visualizations:
    - title: "SNMP Status"
      description: "SNMP Status"
      type: "row"
      columns:
        - type: "stack"
          width: 1
          stacks:
            - title: "Rack 1"
              rows:
                - id: "router"
                  size: "small"
                  layout: 3x1 4x2
                - id: "switch"
                  size: "small"
                  layout: 3x4x2 1
                - id: "switch-core"
                  size: "small"
                  layout: 3x4x2 2x2
        - type: "table"
          width: 3
